[main]
entries = [
   { title = "Most Played", action = { query = "popular", count = 15 } },
   { title = "Favourites", action = { query = "favourites", count = 15 } },
   { title = "Categories", action.query = "categories" },
   { title = "All Games", action.query = "roms" },
   { title = "Fighting Games", action = { query = "roms", genre = "Fighter" } },
   { title = "Shutdown", action = { exec = "sudo", args = ["shutdown"] } },
   { title = "Exit", action = "exit" }
]