[main]
name = "Main"
entries = [
   { title = "System", menu = "system" },
   { title = "Games", menu = "games" }
]

[menus.system]
entries = [
   { title = "Shutdown", exec = "sudo shutdown" }
]

[menus.games]
entries = [
   { title = "Favorites", menu = "ll://favories" },
   { title = "Fighting Games", menu = "fighting_games" },
   { title = "Free Games", menu = "free_games" },
   { title = "Puzzle Games", menu = "puzzle_games" },
   { title = "Sports Games", menu = "sports_games" }
]

[menus.free_games]
entries = [
   { rom = "robby", title = "Robby Roto" }
]

[menus.fighting_games]
entries = [
   { rom = "sf2", title = "Street Fighter II" },
   { rom = "sfa", title = "Stree Fighter Alpha: Warrior's Dream" },
   { rom = "xmvsf", title = "X-Men Vs Street Fighter" },
   { rom = "sf2ce", title = "Street Fight II: CE" },
   { rom = "sfa3", title = "Street Fighter Alpha 3" },
   { rom = "mshvsf", title = "Marvel Super Heros vs Street Fighter" },
   { rom = "sf2ui", title = "Street Fighter II - The World Warrior" },
   { rom = "ga2", title = "Golden Axe - Revenge of Death Adder" },
   { rom = "nbbatman", title = "Ninja Baseball Batman" },
   { rom = "xmvsf", title = "X-Men Vs. Street Fighter" },
   { rom = "simpsn2p", title = "The Simpsons" },
   { rom = "mk", title = "Mortal Combat" },
   { rom = "kinst", title = "Killer Instinct" },
   { rom = "kof98", title = "King of Fighters 98" },
   { rom = "kof95", title = "King of Fighters 95" },
   { rom = "lastblad", title = "Last Blade" },
   { rom = "mvsc", title = "Marvel vs Capcom" },
   { rom = "mk2", title = "Mortal Combat 2" },
   { rom = "sfa2", title = "Street Fight Alpha 2" },
   { rom = "avsp", title = "Alien vs Predator" },
   { rom = "sailormn", title = "Prett Soilder Sailor Moon" },
   { rom = "tmnt", title = "Teenage Mutant Ninja Turtles" },
   { rom = "tmnt2", title = "Teenage Mutant Ninja Turtls 2" },
   { rom = "xmen", title = "X-Men" }
]

[menus.puzzle_games]
entries = [
   { rom = "pbobblen", title = "Puzzle Bobble" },
   { rom = "pbobble2", title = "Puzzle Bobble 2" },
   { rom = "pbobble3", title = "Puzzle Bobble 3" },
   { rom = "pbobble4", title = "Puzzle Bobble 4" },
   { rom = "atetris", title = "Tetris" },
   { rom = "drmario", title = "Vs. Dr. Mario" },
   { rom = "columns", title = "Columns" },
   { rom = "columns2", title = "Columns 2" },
   { rom = "magdrop2", title = "Magic Drop 2" },
   { rom = "magdrop3", title = "Magic Drop 3" }
]

[menus.sports_games]
entries = [
   { rom = "2020bb", title = "2020 Super Baseball" },
   { rom = "cscluba", title = "Capcom Sports Club" },
   { rom = "nbajam", title = "NBA Jam" },
   { rom = "nbahangt", title = "NBA Hang Time" },
   { rom = "openice", title = "2 on 2 Open Ice Challenge" },
   { rom = "neocup98", title = "Neo-Geo Cup 98" },
   { rom = "pwrgoal", title = "Power Goal" }
]