[main]
name = "Main"
entries = [
   { title = "Most Played", action = { query = "popular", count = 15 }, screenshot = "star.png" },
   { title = "Favourites", action = { query = "favourites", count = 15 } },
   { title = "Categories", action = { query = "categories" } },
   { title = "All Games", action = { query = "roms" } },
   { title = "Fighting Games", action = { query = "roms", genre = "Fighter" } },
   { title = "Shutdown", action = { exec = "sudo", args = ["shutdown"] } },
   { title = "Exit", action = "exit" }
]

[menus.games]
entries = [
   { title = "Fighting Games", action = { menu = "fighting_games" } },
   { title = "Free Games", action = { menu = "free_games" } },
   { title = "Puzzle Games", action = { menu = "puzzle_games" } },
   { title = "Sports Games", action = { menu = "sports_games"  } },
   { title = "Airplane Games", action = { menu = "airplane_games"  } },
   { title = "Classic Games", action = { menu = "classic_games"  } },
   { title = "Maze Games", action = { menu = "maze_games"  } },
   { title = "War Games", action = { menu = "war_games"  } },
   { title = "Platform Games", action = { menu = "platform_games"  } }
]

[menus.free_games]
entries = [
   { action = { rom = "robby" }, title = "Robby Roto" }
]

[menus.fighting_games]
entries = [
   { action = { rom = "sf2" }, title = "Street Fighter II" },
   { action = { rom = "sfa" }, title = "Stree Fighter Alpha: Warrior's Dream" },
   { action = { rom = "xmvsf" }, title = "X-Men Vs Street Fighter" },
   { action = { rom = "sf2ce" }, title = "Street Fight II: CE" },
   { action = { rom = "sfa3" }, title = "Street Fighter Alpha 3" },
   { action = { rom = "mshvsf" }, title = "Marvel Super Heros vs Street Fighter" },
   { action = { rom = "sf2ui" }, title = "Street Fighter II - The World Warrior" },
   { action = { rom = "ga2" }, title = "Golden Axe - Revenge of Death Adder" },
   { action = { rom = "nbbatman" }, title = "Ninja Baseball Batman" },
   { action = { rom = "xmvsf" }, title = "X-Men Vs. Street Fighter" },
   { action = { rom = "simpsn2p" }, title = "The Simpsons" },
   { action = { rom = "mk" }, title = "Mortal Combat" },
   { action = { rom = "kinst" }, title = "Killer Instinct" },
   { action = { rom = "kof98" }, title = "King of Fighters 98" },
   { action = { rom = "kof95" }, title = "King of Fighters 95" },
   { action = { rom = "lastblad" }, title = "Last Blade" },
   { action = { rom = "mvsc" }, title = "Marvel vs Capcom" },
   { action = { rom = "mk2" }, title = "Mortal Combat 2" },
   { action = { rom = "sfa2" }, title = "Street Fight Alpha 2" },
   { action = { rom = "avsp" }, title = "Alien vs Predator" },
   { action = { rom = "sailormn" }, title = "Prett Soilder Sailor Moon" },
   { action = { rom = "tmnt" }, title = "Teenage Mutant Ninja Turtles" },
   { action = { rom = "tmnt2" }, title = "Teenage Mutant Ninja Turtls 2" },
   { action = { rom = "xmen" }, title = "X-Men" }
]

[menus.puzzle_games]
entries = [
   { action = { rom = "pbobblen" }, title = "Puzzle Bobble" },
   { action = { rom = "pbobble2" }, title = "Puzzle Bobble 2" },
   { action = { rom = "pbobble3" }, title = "Puzzle Bobble 3" },
   { action = { rom = "pbobble4" }, title = "Puzzle Bobble 4" },
   { action = { rom = "atetris" }, title = "Tetris" },
   { action = { rom = "drmario" }, title = "Vs. Dr. Mario" },
   { action = { rom = "columns" }, title = "Columns" },
   { action = { rom = "columns2" }, title = "Columns 2" },
   { action = { rom = "magdrop2" }, title = "Magic Drop 2" },
   { action = { rom = "magdrop3" }, title = "Magic Drop 3" }
]

[menus.sports_games]
entries = [
   { action = { rom = "2020bb" }, title = "2020 Super Baseball" },
   { action = { rom = "cscluba" }, title = "Capcom Sports Club" },
   { action = { rom = "nbajam" }, title = "NBA Jam" },
   { action = { rom = "nbahangt" }, title = "NBA Hang Time" },
   { action = { rom = "openice" }, title = "2 on 2 Open Ice Challenge" },
   { action = { rom = "neocup98" }, title = "Neo-Geo Cup 98" },
   { action = { rom = "pwrgoal" }, title = "Power Goal" }
]

[menus.airplane_games]
entries = [
   { action = { rom = "1942" }, title = "1942" },
   { action = { rom = "1943" }, title = "1943 - The Battle of Midway" },
   { action = { rom = "cawing" }, title = "Carrier Air Wing" },
   { action = { rom = "batrider" }, title = "Armed Police Batrider" },
   { action = { rom = "agallet" }, title = "Air Gallet" },
   { action = { rom = "19xx" }, title = "19xx: The war Against Destiny" },
   { action = { rom = "s1945p" }, title = "Strikes 1945 Plus" }
]

[menus.classic_games]
entries = [
   { action = { rom = "pacman" }, title = "Pac-Man" },
   { action = { rom = "joust" }, title = "Joust" },
   { action = { rom = "marble" }, title = "Marble Madness" },
   { action = { rom = "ldrun" }, title = "Lode Runner" },
   { action = { rom = "galaga" }, title = "Galaga" },
   { action = { rom = "frogger" }, title = "Frogger" },
   { action = { rom = "arkanoid" }, title = "Arkanoid" },
   { action = { rom = "digbug" }, title = "Dig Dug" },
   { action = { rom = "dkong" }, title = "Donkey Kong" },
   { action = { rom = "galaxian" }, title = "Galaxian" },
   { action = { rom = "mario" }, title = "Mario Bros" },
   { action = { rom = "mspacman" }, title = "Ms. Pac-Man" },
   { action = { rom = "qbert" }, title = "Q*bert" },
   { action = { rom = "arknoid2" }, title = "Arkanoid - Revenge of DOH" },
   { action = { rom = "invaders" }, title = "Space Invaders" },
   { action = { rom = "invadpt2" }, title = "Space Invaders Part II" }
]

[menus.maze_games]
entries = [
   { action = { rom = "pacmania" }, title = "Pac-Mania" },
   { action = { rom = "bombrman" }, title = "Bomberman" },
   { action = { rom = "digdug" }, title = "Dig Dug" },
   { action = { rom = "digdug2" }, title = "Dig Dug II" },
   { action = { rom = "hyperpac" }, title = "Hyper Pac-Man" },
   { action = { rom = "jrpacman" }, title = "Jr. Pac-Man" }
]

[menus.war_games]
entries = [
   { action = { rom = "btlecity" }, title = "Vs. Battle City" },
   { action = { rom = "mslug" }, title = "Metal Slug" },
   { action = { rom = "mslug2" }, title = "Metal Slug 2" },
   { action = { rom = "mslug3" }, title = "Metal Slug 3" },
   { action = { rom = "tankfrce" }, title = "Tank Force" }
]

[menus.platform_games]
entries = [
   { action = { rom = "suprmrio" }, title = "Vs. Super Mario Bros" },
   { action = { rom = "bublbobl" }, title = "Bubble Bobble" },
   { action = { rom = "bublbob2" }, title = "Bubble Bobble 2" },
   { action = { rom = "pacland" }, title = "Pac-Land" },
   { action = { rom = "rampage" }, title = "Rampage" },
   { action = { rom = "shinobi" }, title = "Shinobi" },
   { action = { rom = "wboy" }, title = "Wonder Boy" }
]