size.width = 640
size.height = 480

font.file = "PressStart2P-vaV7.ttf"
font.size = 20

background.image = "background.png"
background.colour = [0x00, 0x00, 0x00]

mame.cmd = "mame"
mame.args = [
   "-rompath",
   "/run/user/1000/gvfs/smb-share:server=freenas,share=bilbo/Storage/Games/Mame/MAME 0.185 ROMs (non-merged)"
]

[menu]
position = { x = 10, y = 10 }
size = { width = 620, height = 420 }
hover_offset = 6
line_height = 30
justify = "center"
text_color = [0xff, 0xff, 0xff]
hover_color = [0x23, 0xc1, 0]

[screenshot]
position = { x = 460, y = 10 }
size = { width = 170, height = 124 }
dir = "/run/user/1000/gvfs/smb-share:server=freenas,share=bilbo/Storage/Games/Mame/MAME_0.142_Titles"

[widgets.favourite]
position = { x = 610, y = 450 }
size = { width = 20, height = 20 }
content = { image = "star.png" }

[widgets.year]
position = { x = 10, y = 450 }
size = { width = 110, height = 24 }

[widgets.manufacturer]
position = { x = 120, y = 450 }
size = { width = 400, height = 24 }
justify = "center"
text_color = [0xe1, 0xdd, 0x14]